<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <script>
        // async函数是js处理异步编程的一种解决方案，很多人认为它是异步操作的终极解决方案。
        // 相较于Promise的优越性：把异步返回的结果从then中拿到【最外层】的方法中，不需要链式调用，用同步的写法处理异步，更直观
        // 简单的说async函数就相当于【自执行的Generator函数】，相当于自带一个状态机，在 await 的部分等待返回， 返回后自动执行下一步。
        // Generator 函数的执行必须靠执行器next()，而async函数自带执行器。
        
        // await 等待的是一个表达式，这个表达式的计算结果是 Promise 对象或者其它值（换句话说，就是没有特殊限定）
        // 如果不是 Promise 对象，就直接返回对应的值。

        // async函数返回的 Promise 对象，必须等到内部所有await命令后面的 Promise 对象执行完，才会发生状态改变，除非遇到return语句或者抛出错误。
        // 也就是说，只有async函数内部的异步操作执行完，才会执行then方法指定的回调函数。

        // 正常情况下，await命令后面是一个 Promise 对象，返回该对象的结果。如果不是 Promise 对象，就直接返回对应的值。


        // 例1
        function timeout1(count) {
            return new Promise((resolve, reject) => {
                // console.log('timeout1');
                setTimeout(() => {
                    resolve(++count)
                }, 500);
            })
        }

        function timeout2(count) {
            return new Promise((resolve, reject) => {
                // console.log('timeout2');
                setTimeout(() => {
                    resolve(++count)
                }, 500);
            })
        }

        function timeout3(count) {
            return new Promise((resolve, reject) => {
                // console.log('timeout3');
                setTimeout(() => {
                    resolve(++count)
                }, 500);
            })
        }


        function computeCount(count) {
            return count + '个'
        }



        async function asyncFn(count) {
            // 异步的，await后面需跟promise对象
            const count1 = await timeout1(count);
            const count2 = await timeout2(count1);
            const count3 = await timeout3(count2).then(res => {
                console.log(res);
                return res
            });
            // 非异步的，有没有await都无所谓
            const count4 = await computeCount(count3);
            const count5 = await 0;
            console.log('count4', count4);
            console.log('count5', count5);
        }

        // await命令后面的 Promise 对象如果变为reject状态，则reject的参数会被async函数的catch方法的回调函数接收到。
        // 任何一个await语句后面的 Promise 对象变为reject状态，那么整个async函数都会【中断执行】。
        asyncFn(1).then(res => {
            console.log('then', res);
        }).catch(err => {
            console.log('err', err);
        });


        // 例2
        function sleep(interval) {
            return new Promise(resolve => {
                setTimeout(resolve, interval);
            })
        }

        // 用法
        async function one2FiveInAsync() {
            for (let i = 1; i <= 10; i++) {
                console.log(i);
                await sleep(1000);
            }
        }
        // one2FiveInAsync();
    </script>
</body>

</html>